//
//  CreateOperationModels.swift
//  Budget
//
//  Created by William Archimède on 29/07/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOperation {
    // MARK: Use cases

    enum Creation {
        struct Request {
            let title: String?
            let amount: String
            let isDeposit: Bool
        }
    }
}
