//
//  CreateOperationPresenter.swift
//  Budget
//
//  Created by William Archimède on 29/07/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOperationPresentationLogic
{
  func presentSomething(response: CreateOperation.Something.Response)
}

class CreateOperationPresenter: CreateOperationPresentationLogic
{
  weak var viewController: CreateOperationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CreateOperation.Something.Response)
  {
    let viewModel = CreateOperation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
