//
//  HistoryInteractor.swift
//  Budget
//
//  Created by William Archimède on 13/08/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryBusinessLogic {
    func getList(request: History.List.Request)
}

class HistoryInteractor: HistoryBusinessLogic {
    var presenter: HistoryPresentationLogic?
    var operationsWorker = OperationsWorker(operationsStore: OperationsCoreDataStore())

    // MARK: Get list and compute amount

    func getList(request: History.List.Request) {
        operationsWorker.fetchAll { [weak self] operations in
            let amount = operations.total()
            let response = History.List.Response(amount: amount, operations: operations)
            self?.presenter?.presentList(response: response)
        }
    }
}
