//
//  HistoryInteractor.swift
//  Budget
//
//  Created by William Archimède on 13/08/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryBusinessLogic {
    func getList(request: History.List.Request)
    func deleteOperation(request: History.Deletion.Request)
}

class HistoryInteractor: HistoryBusinessLogic {
    var presenter: HistoryPresentationLogic?
    var operationsWorker = OperationsWorker(operationsStore: OperationsCoreDataStore())

    // MARK: Get list and compute amount

    fileprivate func fetchAll() {
        operationsWorker.fetchAll { [weak self] operations in
            let amount = operations.total()
            let response = History.List.Response(amount: amount, operations: operations)
            self?.presenter?.presentList(response: response)
        }
    }

    func getList(request: History.List.Request) {
        fetchAll()
    }

    // MARK: Delete operation and update list

    func deleteOperation(request: History.Deletion.Request) {
        operationsWorker.delete(request.operation) { [weak self] error in
            // Not really handling errors for now
            if error != nil {
                return
            }

            self?.operationsWorker.fetchAll { [weak self] operations in
                let amount = operations.total()
                let response = History.Deletion.Response(amount: amount, operation: request.operation)
                self?.presenter?.presentDeletion(response: response)
            }
        }
    }
}
