//
//  CreateOperationViewController.swift
//  Budget
//
//  Created by William Archimède on 29/07/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoogleMobileAds

protocol CreateOperationDisplayLogic: class {
    func displayCreationDone()
}

class CreateOperationViewController: UIViewController, CreateOperationDisplayLogic {
    var interactor: CreateOperationBusinessLogic?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let interactor = CreateOperationInteractor()
        let presenter = CreateOperationPresenter()
        self.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = self
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupAdBannerView()
    }

    // MARK: Create operation

    @IBAction func createOperation(_ sender: Any) {
        let request = CreateOperation.Creation.Request(title: "test", amount: "10", isWithdrawal: true)
        interactor?.createOperation(request: request)
    }

    func displayCreationDone() {
        navigationController?.popViewController(animated: true)
    }

    // MARK: - Admob

    @IBOutlet weak var adBannerView: GADBannerView!

    private func setupAdBannerView() {
        adBannerView.rootViewController = self
        adBannerView.adUnitID = "ca-app-pub-3940256099942544/6300978111" // Test
        //        adBannerView.adUnitID = "ca-app-pub-7814673314543067/2788088095" // Prod
        adBannerView.load(GADRequest())
    }
}
