//
//  CreateOperationInteractor.swift
//  Budget
//
//  Created by William Archimède on 29/07/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOperationBusinessLogic
{
  func doSomething(request: CreateOperation.Something.Request)
}

protocol CreateOperationDataStore
{
  //var name: String { get set }
}

class CreateOperationInteractor: CreateOperationBusinessLogic, CreateOperationDataStore
{
  var presenter: CreateOperationPresentationLogic?
  var worker: CreateOperationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreateOperation.Something.Request)
  {
    worker = CreateOperationWorker()
    worker?.doSomeWork()
    
    let response = CreateOperation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
