//
//  CreateOperationRouter.swift
//  Budget
//
//  Created by William Archimède on 29/07/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateOperationRoutingLogic {

    func routeToBalance()
}

class CreateOperationRouter: NSObject, CreateOperationRoutingLogic {
    weak var viewController: CreateOperationViewController?

    // MARK: Routing & navigation

    func routeToBalance() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
