//
//  OperationWorker.swift
//  Budget
//
//  Created by William Archimède on 27/07/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class OperationWorker {
    var operationStore: OperationStoreProtocol

    init(operationStore: OperationStoreProtocol) {
        self.operationStore = operationStore
    }

    func fetchAll(completion: @escaping ([Operation]) -> Void) {
        operationStore.fetchAll { operations, _ in // Not handling errors for now.
            completion(operations ?? [])
        }
    }

    func create(_ operation: Operation, completion: @escaping (OperationStoreError?) -> Void) {
        operationStore.create(operation, completion: completion)
    }

    func delete(_ operation: Operation, completion: @escaping (OperationStoreError?) -> Void) {
        operationStore.delete(operation, completion: completion)
    }
}

protocol OperationStoreProtocol {
    func fetchAll(completion: @escaping ([Operation]?, OperationStoreError?) -> Void)
    func create(_ operation: Operation, completion: @escaping (OperationStoreError?) -> Void)
    func delete(_ operation: Operation, completion: @escaping (OperationStoreError?) -> Void)
}

enum OperationStoreError: Error {
    case cannotFetch(String)
    case cannotCreate(String)
    case cannotDelete(String)
}
