//
//  BalanceViewController.swift
//  Budget
//
//  Created by William Archimède on 20/07/2017.
//  Copyright (c) 2017 William Archimede. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BalanceDisplayLogic: class {
    func displayAmount(viewModel: Balance.Amount.ViewModel)
}

class BalanceViewController: UIViewController, BalanceDisplayLogic {
    var interactor: BalanceBusinessLogic?
    var router: (NSObjectProtocol & BalanceRoutingLogic & BalanceDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = BalanceInteractor()
        let presenter = BalancePresenter()
        let router = BalanceRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        getAmount()
    }

    // MARK: Display balance amount

    @IBOutlet weak var balanceButton: UIButton!

    func getAmount() {
        let request = Balance.Amount.Request()
        interactor?.getAmount(request: request)
    }

    func displayAmount(viewModel: Balance.Amount.ViewModel) {
        balanceButton.setTitle(viewModel.amount, for: .normal)
    }
}
